In [16]:
from os.path import expanduser
home = expanduser('~')
import numpy as np

from pymatgen.io.vasp.outputs import Eigenval, Outcar

In [37]:
### Settings
loc = home + '/Projects/BaCoS2/correct_mag/Pba2-phonons/U2/outputs'


### Reading data
for disp in range(1,25):
    
    ### Band gap
    eig = Eigenval(f'{loc}/{disp}/EIGENVAL')
    print(f'\nBand gap = {np.round(eig.eigenvalue_band_properties[0],3)}')
    
    ### Magnetic details
    out = Outcar(f'{loc}/{disp}/OUTCAR')
    unique, counts = np.unique(np.round([mag["tot"] for mag in out.magnetization[16:32]], 1), 
                               return_counts=True)
    print(f'{np.asarray((unique,counts)).T}')    


Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.027
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.027
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.027
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]

Band gap = 0.028
[[-2.  8.]
 [ 2.  8.]]
